export const tours =[
    {
        "id":1,
        "name": "Cuba Sailing Adventure",
        "type": "Adventure",
        "price": 101.00,
        "discount": 12,
        "featured": true,
        "duration": "5 days",
        "rate": 4.8,
        "reviwes": "1.6k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-1.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":2,
        "name": "Beautiful parasailing",
        "address": "traford Park Lexington,40507",
        "price": 181.00,
        "discount": 0,
        "featured": true,
        "rate": 4.8,
        "reviwes": "1.6k",
        "img": "/tours/tour-2.jpg",
        "type": "Adventure",
        "duration": "2 days",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":3,
        "name": "Cuba Sailing Adventure",
        "type": "Adventure",
        "price": 171.00,
        "discount": 15,
        "featured": false,
        "duration": "3 days",
        "rate": 4.8,
        "reviwes": "1.6k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-3.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":4,
        "name": "Sight seeing & taj Mahal..",
        "type": "Adventure",
        "price": 171.00,
        "discount": 0,
        "featured": true,
        "duration": "5 days",
        "rate": 4.5,
        "reviwes": "1.7k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-4.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":5,
        "name": "Peninsula & Caribbean..",
        "type": "Adventure",
        "price": 151.00,
        "discount": 12,
        "featured": true,
        "duration": "4 days",
        "rate": 4.7,
        "reviwes": "1.2k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-5.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":6,
        "name": "Boathouse Neighborhood",
        "type": "Adventure",
        "price": 151.00,
        "discount": 12,
        "featured": false,
        "duration": "8 days",
        "rate": 4.7,
        "reviwes": "1.2k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-6.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":7,
        "name": "Cuba Sailing Adventure",
        "type": "Adventure",
        "price": 101.00,
        "discount": 12,
        "featured": true,
        "duration": "5 days",
        "rate": 4.8,
        "reviwes": "1.6k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-7.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":8,
        "name": "Beautiful parasailing",
        "address": "traford Park Lexington,40507",
        "price": 181.00,
        "discount": 0,
        "featured": true,
        "rate": 4.8,
        "reviwes": "1.6k",
        "img": "/tours/tour-8.jpg",
        "type": "Adventure",
        "duration": "2 days",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":9,
        "name": "Cuba Sailing Adventure",
        "type": "Adventure",
        "price": 171.00,
        "discount": 15,
        "featured": false,
        "duration": "3 days",
        "rate": 4.8,
        "reviwes": "1.6k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-9.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":10,
        "name": "Sight seeing & taj Mahal..",
        "type": "Adventure",
        "price": 171.00,
        "discount": 0,
        "featured": true,
        "duration": "5 days",
        "rate": 4.5,
        "reviwes": "1.7k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-10.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":11,
        "name": "Peninsula & Caribbean..",
        "type": "Adventure",
        "price": 151.00,
        "discount": 12,
        "featured": true,
        "duration": "4 days",
        "rate": 4.7,
        "reviwes": "1.2k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-11.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":12,
        "name": "Boathouse Neighborhood",
        "type": "Adventure",
        "price": 151.00,
        "discount": 12,
        "featured": false,
        "duration": "8 days",
        "rate": 4.7,
        "reviwes": "1.2k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-12.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":13,
        "name": "Cuba Sailing Adventure",
        "type": "Adventure",
        "price": 101.00,
        "discount": 12,
        "featured": true,
        "duration": "5 days",
        "rate": 4.8,
        "reviwes": "1.6k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-13.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":14,
        "name": "Discovery island kayak..",
        "type": "Adventure",
        "price": 181.00,
        "discount": 0,
        "featured": true,
        "duration": "2 days",
        "rate": 4.8,
        "reviwes": "1.6k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-14.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    },
    {
        "id":15,
        "name": "Beautiful parasailing",
        "type": "Adventure",
        "price": 171.00,
        "discount": 15,
        "featured": false,
        "duration": "3 days",
        "rate": 4.8,
        "reviwes": "1.6k",
        "address": "traford Park Lexington,40507",
        "img": "/tours/tour-15.jpg",
        "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta. Et malesuada fames ac turpis egestas sed. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Cras semper auctor neque vitae. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus et netus. Ut morbi tincidunt augue interdum velit euismod. At in tellus integer feugiat scelerisque varius morbi. Ultrices neque ornare aenean euismod. Imperdiet proin fermentum leo",
        "facilities": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "challenge": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua At volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta",
        "include": ["Pick and Drop Services", "1 Meal Per Day", "Cruise Dinner & Music Event", "Visit 7 Best Places in the City With Group"],
        "exclude": ["Additional Services", "Insurance", "Food & Drinks", "Tickets"],
        "info": {
            "maxGuests": "Date",
            "minAge": "12+",
            "location": "Americe",
            "language": "Global"
        }
    }
];